apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
    name: http
  selector:
    app: {{ .Release.Name }}
    component: backend
