{{- if .Values.basicAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-basic-auth" .Release.Name) .Values.basicAuth.secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ .Files.Get .Values.basicAuth.authFile | b64enc }}
{{- end }}

