apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  # htpasswd file content, base64-encoded
  auth: {{ .Files.Get "auth/htpasswd" | b64enc }}

