apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName | quote }}
  namespace: {{ .Release.Name }}
spec:
  dnsNames:
    - {{ .Values.ingress.host | quote }}
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: duckdns-github-production
  renewBefore: 360h
  secretName: {{ .Values.ingress.tls.secretName | quote }}
  subject:
    organizations:
      - friclu
