apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fabric
spec:
  ingressClassName: nginx
  rules:
    - host: fabric.friclu
      http:
        paths:
          - backend:
              service:
                name: fabric-ui
                port:
                  number: {{ .Values.ui.port }}
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: fabric-backend
                port:
                  number: {{ .Values.backend.port }}
            path: /backend
            pathType: ImplementationSpecific
{{/*  tls:*/}}
{{/*    - hosts:*/}}
{{/*        - ha-friclu.duckdns.org*/}}
{{/*      secretName: ha-certificate*/}}
