apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.backend.fabricFiles }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
