apiVersion: v1
kind: PersistentVolume
metadata:
  name: sync
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /volumes/syncthing/Sync
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
