apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: sync
