apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ui-scripts
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    component: ui
data:
  # UI application JavaScript
  app.js: |-
{{ .Files.Get "scripts/app.js" | replace "const apiDomain = 'http://localhost:8080';" (printf "const apiDomain = '%s';" ( tpl .Values.ui.backendUrl . )  ) | indent 4 }}
  # UI HTML entrypoint
  index.html: |-
{{ .Files.Get "scripts/index.html" | indent 4 }}
  # PWA manifest with configurable icon path
  manifest.json: |-
    {
      "name": "{{ .Values.ui.title }}",
      "short_name": "{{ .Values.ui.title }}",
      "start_url": "./index.html",
      "display": "standalone",
      "background_color": "#ffffff",
      "theme_color": "#0d6efd",
      "icons": [
        {
          "src": "{{ .Values.ui.iconPath }}/icon-192.png",
          "sizes": "192x192",
          "type": "image/png"
        },
        {
          "src": "{{ .Values.ui.iconPath }}/icon-512.png",
          "sizes": "512x512",
          "type": "image/png"
        }
      ]
    }
  # Service worker
  service-worker.js: |-
{{ .Files.Get "scripts/service-worker.js" | indent 4 }}
