apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}
    component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: ui
    spec:
      containers:
      - name: fabric-ui
        env:
          - name: API_DOMAIN
            value: {{ .Values.ui.backendUrl }}
        image: "{{ .Values.ui.image }}:{{ .Values.ui.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ui.port }}
        volumeMounts:
        - name: ui-scripts
          mountPath: /usr/share/nginx/html
          # mounts app.js and index.html from ConfigMap into web root
      volumes:
      - name: ui-scripts
        configMap:
          name: {{ .Release.Name }}-ui-scripts
          defaultMode: 0644
